
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS buyers;
CREATE TABLE buyers (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, login VARCHAR (32), password VARCHAR (32), email VARCHAR (32));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
